config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => :registrations }
  root to: 'visitors#index'
  get '/dashboard', to: 'users#dashboard'
  get '/finances', to: 'users#finances'

  resources :supplies, :only => [:index, :create, :new, :edit, :destroy, :update]
  
  get '/supplies/new/:kind', to: 'supplies#new', as: :new_specific_supply
  get 'supplies/:kind' => 'supplies#show_kind', as: :show_supply
  delete 'supplies/:kind/:id' => 'supplies#destroy', as: :destroy_supply

  # resources :fields do
  #   resources :treatments, :harvest_loads
  # end

  resources :fields
  resources :activities
  resources :crop_prices, only: [:index]

  get '/fields/:id/treatments/new', to: 'treatments#new', as: :new_treatment
  post '/fields/:id/treatments/new', to: 'treatments#create', as: :create_treatment
  get '/fields/:id/treatments/:treatment_id', to: 'treatments#show', as: :show_treatment
  get '/fields/:id/treatments/:treatment_id/edit', to: 'treatments#edit', as: :edit_treatment
  patch '/fields/:id/treatments/:treatment_id/edit', to: 'treatments#update', as: :update_treatment
  delete '/fields/:id/treatments/:treatment_id', to: 'treatments#destroy', as: :destroy_treatment

  get '/fields/:id/harvest_loads/new', to: 'harvest_loads#new', as: :new_harvest_load
  post '/fields/:id/harvest_loads/new', to: 'harvest_loads#create', as: :create_harvest_load
  get '/fields/:id/harvest_loads/:harvest_load_id/edit', to: 'harvest_loads#edit', as: :edit_harvest_load
  patch '/fields/:id/harvest_loads/:harvest_load_id/edit', to: 'harvest_loads#update', as: :update_harvest_load
  delete '/fields/:id/harvest_loads/:harvest_load_id', to: 'harvest_loads#destroy', as: :destroy_harvest_load
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :field
  belongs_to :supply

  validates_presence_of :field_id
  validates_presence_of :supply_id
  validates_presence_of :quantity
  validates_presence_of :date
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_info

  def find_user_info
    @fields = current_user.fields.all
    @field = Field.find(params[:id])
    @supplies = current_user.supplies.all
  end

  def create
    @field = Field.find(params[:id])
    @treatment = @field.treatments.create(treatment_params)
    @fields = current_user.fields.all
    if @treatment.save
      @treatment.create_activity :create, owner: current_user
      flash[:notice] = "#{@treatment.supply.name} has been added to your field."
      redirect_to field_path(@field)
    else
      flash[:alert] = "Treatment could not be added."
      redirect_to new_field_path
    end
  end

  def destroy
    @id = params[:treatment_id]
    # Treatment.find(@id).create_activity :destroy, owner: current_user
    Treatment.destroy(@id)
    redirect_to :back
  end

  def edit
    @treatment = Treatment.find(params[:treatment_id])
  end

  def new
    @treatment = Treatment.new
  end

  def show
    @field = Field.find(params[:id])
    @treatment = Treatment.find(params[:treatment_id])
  end

  def update
    @field = Field.find(params[:id])
    @treatment = Treatment.find(params[:treatment_id])
    if @treatment.update(treatment_params)
      flash[:notice] = "Treatment record was updated successfully."
      redirect_to field_path(@field)
    else
      flash[:alert] = "Treatment could not be updated."
      render edit_field_path(@field)
    end
  end

  protected

  def treatment_params
    params.require(:treatment).permit(:supply_id, :date, :quantity)
  end
end

app/views/treatments/edit.html.haml
%h2= "Edit Treatment Details"

= simple_form_for @treatment, :url => update_treatment_path do |f|
  = f.error_notification
  .form-inputs
    = f.input :supply_id, collection: @supplies, :prompt => "Select from supplies", required: true
    = f.input :date, as: :date, required: true
    = f.input :quantity, as: :integer, label: "Total Applied", required: true
    = f.input :notes, as: :text
  .form-actions
    = f.button :submit, "Save Treatment"

app/views/treatments/new.html.haml
%h2= "New Treatment"

= simple_form_for @treatment, :url => create_treatment_path do |f|
  = f.error_notification
  .form-inputs
    = f.input :supply_id, collection: @supplies, :prompt => "Select from supplies", required: true
    = f.input :date, as: :date, required: true
    = f.input :quantity, as: :integer, label: "Total Applied", required: true
    = f.input :notes, as: :text
  .form-actions
    = f.button :submit, "Save Treatment"

app/views/treatments/show.html.haml
.page-title
  %h1= "Treatment Details"

  = link_to "Edit", "/fields/#{@field.id}/treatments/#{@treatment.id}/edit", class: "btn"
  = link_to "Delete", "/fields/#{@field.id}/treatments/#{@treatment.id}", method: :delete, data: { confirm: "Are you certain you want to delete #{@treatment.supply.name} entry?" }, class: "btn"

.treatment-container
  %h4= "Field: "
  %p.number-good= "#{@field.name}"
  .clear
  %h4= "Application: "
  %p.number-good= "#{@treatment.supply.name}"
  .clear

  %h4= "Measurement: "
  %p.number-good= "#{@treatment.supply.measure}"
  .clear

  %h4= "Total Applied: "
  %p.number-good= "#{@treatment.quantity}"
  .clear

  %h4= "Total Applied Per Acre: "
  %p.number-good= "#{(@treatment.quantity / @field.acreage)}"

  .border
  %h4= "Unit Cost: "
  %p.number-good= "#{number_to_currency(@treatment.supply.unit_cost)}"
  .clear

  %h4= "Cost Per Acre: "
  %p.number-good= "#{number_to_currency(@treatment.supply.unit_cost * (@treatment.quantity / @field.acreage))}"
  .clear

  %h4= "Total Cost: "
  %p.number-good= "#{number_to_currency(@treatment.supply.unit_cost * @treatment.quantity)}"
  .clear