config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => :registrations }
  root to: 'visitors#index'
  get '/dashboard', to: 'users#dashboard'
  get '/finances', to: 'users#finances'

  resources :supplies, :only => [:index, :create, :new, :edit, :destroy, :update]
  
  get '/supplies/new/:kind', to: 'supplies#new', as: :new_specific_supply
  get 'supplies/:kind' => 'supplies#show_kind', as: :show_supply
  delete 'supplies/:kind/:id' => 'supplies#destroy', as: :destroy_supply

  # resources :fields do
  #   resources :treatments, :harvest_loads
  # end

  resources :fields
  resources :activities
  resources :crop_prices, only: [:index]

  get '/fields/:id/treatments/new', to: 'treatments#new', as: :new_treatment
  post '/fields/:id/treatments/new', to: 'treatments#create', as: :create_treatment
  get '/fields/:id/treatments/:treatment_id', to: 'treatments#show', as: :show_treatment
  get '/fields/:id/treatments/:treatment_id/edit', to: 'treatments#edit', as: :edit_treatment
  patch '/fields/:id/treatments/:treatment_id/edit', to: 'treatments#update', as: :update_treatment
  delete '/fields/:id/treatments/:treatment_id', to: 'treatments#destroy', as: :destroy_treatment

  get '/fields/:id/harvest_loads/new', to: 'harvest_loads#new', as: :new_harvest_load
  post '/fields/:id/harvest_loads/new', to: 'harvest_loads#create', as: :create_harvest_load
  get '/fields/:id/harvest_loads/:harvest_load_id/edit', to: 'harvest_loads#edit', as: :edit_harvest_load
  patch '/fields/:id/harvest_loads/:harvest_load_id/edit', to: 'harvest_loads#update', as: :update_harvest_load
  delete '/fields/:id/harvest_loads/:harvest_load_id', to: 'harvest_loads#destroy', as: :destroy_harvest_load
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :user

  validates_presence_of :kind
  validates_presence_of :name
  validates_presence_of :purchase_date
  validates_presence_of :vendor
  validates_presence_of :measure
  validates_presence_of :price

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_supplies

  def find_user_supplies
    @supplies = current_user.supplies.all
  end

  def index
    @total = @supplies.sum(:price)

    @chemical_total = @supplies.where(kind: "chemical").sum(:price)
    @fertilizer_total = @supplies.where(kind: "fertilizer").sum(:price)
    @seed_total = @supplies.where(kind: "seed").sum(:price)
    @other_total = @supplies.where(kind: "other").sum(:price)

  end

  def create
    @supply = current_user.supplies.create(supply_params)
    if @supply.price && @supply.quantity
      @supply.create_activity :create, owner: current_user
      @supply.unit_cost = (@supply.price / @supply.quantity).round(2)
    end
    @supplies = current_user.supplies.all
    if @supply.save
      flash[:notice] = "#{@supply.name} purchase has been added to your supplies."
      redirect_to "/supplies/#{@supply.kind}"
    else
      flash[:alert] = "Purchase could not be added."
      redirect_to new_supply_path
    end
  end

  def destroy
    @kind = params[:kind]
    @id = params[:id]
    Supply.destroy(@id)
    redirect_to :back
  end

  def edit
    @supply = Supply.find(params[:id])
  end

  def new
    @supply = Supply.new
    @kind = params[:kind]
  end

  def update
    @supply = Supply.find(params[:id])
    if @supply.update(supply_params)
      flash[:notice] = "#{@supply.name} has been updated."
      redirect_to "/supplies/#{@supply.kind}"
    else
      flash[:alert] = "Purchase could not be updated."
      render edit_supply_path(@supply)
    end
  end

  def show_kind
    @kind = params[:kind]
    @list = @supplies.where(kind: "#{@kind}")
    @list_total = @list.sum(:price)
    render 'supplies/specific'
  end

  protected

  def supply_params
    params.require(:supply).permit(:kind, :name, :purchase_date, :vendor, :measure, :price, :quantity)
  end
end

app/views/supplies/edit.html.haml
.page-title
  - if @kind == nil
    %h1= "Edit Supply Details"
  - else
    %h1= "Edit #{@kind.capitalize} Details"

= simple_form_for @supply do |f|
  = f.error_notification
  .form-inputs
    - if @kind == nil
      = f.input :kind, collection: ["chemical", "fertilizer", "seed", "other"], prompt: "What did you buy?", required: true
    - else
      = f.input :kind, collection: ["#{@kind}"], default: 1, required: true
    = f.input :name, required: true, autofocus: true
    = f.input :purchase_date, as: :date, required: true
    = f.input :vendor, required: true
    = f.input :measure, collection: ["oz", "qt", "lb", "bag", "acre", "other"], prompt: "Select the measurement", required: true
    = f.input :quantity, as: :integer, required: true
    = f.input :price, as: :decimal, required: true
  .border
  .form-actions
    = f.button :submit, "Update Purchase"

app/views/supplies/index.html.haml
.page-title
  %h1 SUPPLIES

  = link_to "Add Purchase", new_supply_path, class: "btn"

- if @supplies.empty?
  %p You currently have not purchased any supplies
  = link_to "Add your first purchase", new_supply_path, class: "btn-big"

.supply-title
  %h2 
    = link_to "Chemicals", 'supplies/chemical', class: "supply-kind"
    = link_to "SHOW ALL", 'supplies/chemical', class: "btn"
  %p.amount= "#{number_to_currency(@chemical_total)}"

.supply-title
  %h2
    = link_to "Fertilizer", 'supplies/fertilizer', class: "supply-kind"
    = link_to "SHOW ALL", 'supplies/fertilizer', class: "btn"
  %p.amount= "#{number_to_currency(@fertilizer_total)}"

.supply-title
  %h2
    = link_to "Seed", 'supplies/seed', class: "supply-kind"
    = link_to "SHOW ALL", 'supplies/seed', class: "btn"
  %p.amount= "#{number_to_currency(@seed_total)}"

.supply-title
  %h2
    = link_to "Other", 'supplies/other_supplies', class: "supply-kind"
    = link_to "SHOW ALL", 'supplies/other_supplies', class: "btn"
  %p.amount= "#{number_to_currency(@other_total)}"

.total
  %p.total-cost= "Total Cost: "
  %p= "#{number_to_currency(@total)}"

app/views/supplies/new.html.haml
.page-title.new
  - if @kind == nil
    %h1= "New Supplies Purchase"
  - else
    %h1= "New #{@kind.capitalize} Purchase"

= simple_form_for(@supply) do |f|
  = f.error_notification
  .form-inputs
    - if @kind == nil
      = f.input :kind, collection: ["chemical", "fertilizer", "seed", "other"], prompt: "What did you buy?", required: true
    - else
      = f.input :kind, collection: ["#{@kind}"], default: 1, required: true
    = f.input :name, required: true, autofocus: true
    = f.input :purchase_date, as: :date, required: true
    = f.input :vendor, required: true
    = f.input :measure, collection: ["oz", "qt", "lb", "bag", "acre", "other"], prompt: "Select the measurement", required: true
    = f.input :quantity, as: :integer, required: true
    = f.input :price, as: :decimal, required: true
  .form-actions
    .border  
    = f.button :submit, "Add Purchase", class: "btn-big center"

app/views/supplies/specific.html.haml
.page-title
  %h3 SUPPLIES
  %i.glyphicon.glyphicon-play
  %h1= "#{@kind.pluralize.upcase}"
  = link_to "Add Purchase", new_specific_supply_path, class: "btn"

- if @list.length > 0
  %table.supplies-list
    %thead
      %tr
        %th.header= "Date"
        %th.header= "#{@kind.capitalize}"
        %th.header= "Vendor"
        %th.header= "Measure"
        %th.header= "Quantity"
        %th.header= "Price"
        %th.header= "Cost Per"
        %th
        %th
    %tbody
      - @list.each do |entry|
        %tr.supplies-entry
          %td= entry.purchase_date
          %td= entry.name
          %td= entry.vendor
          %td= entry.measure
          %td= entry.quantity
          %td= "#{number_to_currency(entry.price)}"
          %td= "#{number_to_currency(entry.price.to_f / entry.quantity.to_f)}"
          %td
            = link_to "Delete", "#{@kind}/#{entry.id}", method: :delete, data: { confirm: "Are you certain you want to delete #{entry.name}?" }
          %td
            = link_to "Edit", edit_supply_path(entry)

  .border
  %p.inline TOTAL:
  %p.inline.total-amount= "#{number_to_currency(@list_total)}"

- else
  %h3= "You have not yet purchased any #{@kind.pluralize}"
  = link_to "Add Your First Purchase", new_specific_supply_path